### ISSUE TITLE
KRC: Align Spectral plots w/ Kristen's color scheme

### ISSUE THREAD

**Issue by kevincovey** [krislars/AA_Tau_Covey#22]
Grey = 2008
Black = Dec 2 2014
Red = Dec 12 2014
NO BLUE OR GREEN

**Comment by krislars** [comment]
Blue = 2 mag Av model
Green = 4 mag Av model

**Comment by krislars** [comment]
@kevincovey 
NEW COLOR SCHEME:
Grey or black = 2008
Red = Dec 2 2014
Orange = Dec 12 2014

Blue = 2 mag Av model
Green = 4 mag Av model

**Comment by kevincovey** [comment]
done and done.
